spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/hello-pizza
    username: common-user
    password: 123pass123
  flyway:
    url: jdbc:postgresql://localhost:5432/hello-pizza
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
application:
  core:
    error:
      size-already-exists-key: "size-already-exists"
      topping-already-exists-key: "topping-already-exists"
